resolver: lts-22.42

packages:
  - .

extra-deps:
  - docopt-0.7.0.8

  - github: lehins/hip
    commit: ddfc77feb21722babccd3b3aa73c4c3d41268f54
    subdirs:
      - hip

  - github: lehins/Color
    commit: ec833edd8f9b15543855c00826c4ede470773f83
    subdirs:
      - Color

  - github: ad-si/Brillo
    commit: 932dd2c20e713591d4658a8b7cc0b00478d3e70b
    subdirs:
      - brillo
      - brillo-algorithms
      - brillo-juicy
      - brillo-rendering

allow-newer: true
