resolver: nightly-2022-06-11

packages:
  - .

extra-deps:
  - docopt-0.7.0.7

  - git: https://github.com/hpacheco/gloss-juicy
    commit: acbdfd864b7e574dfbe1595fbdcd154563b2a0ef

  - gloss-1.13.2.1

  - hsexif-0.6.1.8

  - git: https://github.com/protolude/protolude
    commit: 3e249724fd0ead27370c8c297b1ecd38f92cbd5b

flags:
  gloss:
    glfw: true

allow-newer: true
