resolver: lts-22.42

packages:
  - .

extra-deps:
  - docopt-0.7.0.8

  - github: hpacheco/gloss-juicy
    commit: acbdfd864b7e574dfbe1595fbdcd154563b2a0ef

  - github: lehins/hip
    commit: ddfc77feb21722babccd3b3aa73c4c3d41268f54
    subdirs:
      - hip

  - github: lehins/Color
    commit: ec833edd8f9b15543855c00826c4ede470773f83
    subdirs:
      - Color

flags:
  gloss:
    glfw: true

allow-newer: true
